// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Id } from "../../libs/Id.sol";

/**
 * @title IEntitySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntitySystem {
  function evefrontier__registerClass(Id classId, Id[] memory systemTags) external;

  function evefrontier__deleteClass(Id classId) external;

  function evefrontier__deleteClasses(Id[] memory classIds) external;

  function evefrontier__instantiate(Id classId, Id objectId) external;

  function evefrontier__deleteObject(Id objectId) external;

  function evefrontier__deleteObjects(Id[] memory objectIds) external;
}
