// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TagId } from "../../libs/TagId.sol";
import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";
import { TagParams } from "../../namespaces/evefrontier/systems/tag-system/types.sol";

/**
 * @title ITagSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITagSystem {
  error Tag_InvalidTagId(TagId tagId);
  error Tag_TagDoesNotExist(TagId tagId);
  error Tag_TagNotFound(uint256 entityId, TagId tagId);
  error Tag_TagTypeNotDefined(bytes2 tagType);
  error Tag_ResourceNotRegistered(ResourceId systemId);
  error Tag_EntityAlreadyHasTag(uint256 entityId, TagId tagId);
  error Tag_InvalidCaller(address caller);
  error Tag_OnlyClassOrObjectPropertyAllowed();
  error Tag_EntityDoesNotExist(uint256 entityId);

  function evefrontier__setTag(uint256 entityId, TagParams memory tagParams) external;

  function evefrontier__setTags(uint256 entityId, TagParams[] memory tagParams) external;

  function evefrontier__removeTag(uint256 entityId, TagId tagId) external;

  function evefrontier__removeTags(uint256 entityId, TagId[] memory tagIds) external;
}
