// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SmartAssembly, SmartAssemblyData } from "./tables/SmartAssembly.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { StaticData } from "./tables/StaticData.sol";
import { StaticDataMetadata } from "./tables/StaticDataMetadata.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharacterToken } from "./tables/CharacterToken.sol";
import { Balances } from "./tables/Balances.sol";
import { ERC721Metadata, ERC721MetadataData } from "./tables/ERC721Metadata.sol";
import { TokenURI } from "./tables/TokenURI.sol";
import { Owners } from "./tables/Owners.sol";
import { TokenApproval } from "./tables/TokenApproval.sol";
import { OperatorApproval } from "./tables/OperatorApproval.sol";
import { ERC721Registry } from "./tables/ERC721Registry.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployableState, GlobalDeployableStateData } from "./tables/GlobalDeployableState.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { DeployableTokenTable } from "./tables/DeployableTokenTable.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
