// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { StaticData } from "./tables/StaticData.sol";
import { StaticDataMetadata, StaticDataMetadataData } from "./tables/StaticDataMetadata.sol";
import { Location, LocationData } from "./tables/Location.sol";
