// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityRecordParams, EntityMetadataParams } from "../../namespaces/evefrontier/systems/entity-record/types.sol";

/**
 * @title IEntityRecordSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntityRecordSystem {
  function evefrontier__createRecord(uint256 smartObjectId, EntityRecordParams memory entityRecordParams) external;

  function evefrontier__createMetadata(
    uint256 smartObjectId,
    EntityMetadataParams memory entityRecordMetadata
  ) external;

  function evefrontier__setName(uint256 smartObjectId, string memory name) external;

  function evefrontier__setDappURL(uint256 smartObjectId, string memory dappURL) external;

  function evefrontier__setDescription(uint256 smartObjectId, string memory description) external;
}
