// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityRecordData, EntityMetadata } from "../../namespaces/eveworld/systems/entity-record/types.sol";

/**
 * @title IEntityRecordSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntityRecordSystem {
  function eveworld__createEntityRecord(EntityRecordData memory entityRecord) external;

  function eveworld__createEntityRecordMetadata(EntityMetadata memory entityRecordMetadata) external;

  function eveworld__setName(uint256 entityId, string memory name) external;

  function eveworld__setDappURL(uint256 entityId, string memory dappURL) external;

  function eveworld__setDescription(uint256 entityId, string memory description) external;
}
