// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { FuelParams } from "../../namespaces/evefrontier/systems/fuel/types.sol";

/**
 * @title IFuelSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFuelSystem {
  error Fuel_InvalidFuelUnitVolume(uint256 smartObjectId, uint256 fuelUnitVolume, uint256 min, uint256 max);
  error Fuel_InvalidFuelMaxCapacity(uint256 smartObjectId, uint256 fuelMaxCapacity, uint256 min, uint256 max);
  error Fuel_InvalidFuelAmount(uint256 smartObjectId, uint256 fuelAmount, uint256 min, uint256 max);
  error Fuel_ExceedsMaxCapacity(
    uint256 smartObjectId,
    uint256 fuelAmount,
    uint256 totalProjectedCapacity,
    uint256 maxCapacity
  );
  error Fuel_InsufficientFuel(uint256 smartObjectId, uint256 fuelAmount, uint256 availableFuel);
  error Fuel_InvalidFuelBurnRate(uint256 smartObjectId, uint256 fuelBurnRateInSeconds, uint256 min, uint256 max);
  error Fuel_InvalidFuelTypeId(uint256 smartObjectId, uint256 fuelTypeId, uint256 min, uint256 max);
  error Fuel_InvalidFuelEfficiency(uint256 fuelTypeId, uint256 fuelEfficiency, uint256 min, uint256 max);
  error Fuel_BurnAlreadyStopped(uint256 smartObjectId);
  error Fuel_BurnNotActive(uint256 smartObjectId);

  function evefrontier__configureFuelParameters(uint256 smartObjectId, FuelParams memory fuelParams) external;

  function evefrontier__configureFuelEfficiency(uint256 fuelTypeId, uint256 fuelEfficiency) external;

  function evefrontier__depositFuel(uint256 smartObjectId, uint256 fuelAmount) external;

  function evefrontier__withdrawFuel(uint256 smartObjectId, uint256 fuelAmount) external;

  function evefrontier__startBurn(uint256 smartObjectId) external;

  function evefrontier__stopBurn(uint256 smartObjectId) external;

  function evefrontier__setFuelUnitVolume(uint256 smartObjectId, uint256 fuelUnitVolume) external;

  function evefrontier__setFuelMaxCapacity(uint256 smartObjectId, uint256 fuelMaxCapacity) external;

  function evefrontier__setFuelAmount(uint256 smartObjectId, uint256 fuelAmount) external;

  function evefrontier__updateFuel(uint256 smartObjectId) external;

  function evefrontier__getCurrentFuelConsumptionStatus(
    uint256 smartObjectId
  )
    external
    view
    returns (uint256 timeLeft, uint256 unitsToConsume, uint256 actualConsumptionRateInSeconds, uint256 fuelAmount);
}
