// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "../../namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IInventoryInteractSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInventoryInteractSystem {
  function evefrontier__transferToInventory(
    uint256 smartObjectId,
    uint256 toObjectId,
    InventoryItemParams[] memory items
  ) external;

  function evefrontier__setTransferToInventoryAccess(
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) external;
}
