// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TransferItem } from "../../systems/inventory/types.sol";

/**
 * @title IInventoryInteractSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInventoryInteractSystem {
  error Inventory_InvalidTransferItemQuantity(
    string message,
    uint256 smartObjectId,
    string inventoryType,
    address inventoryOwner,
    uint256 inventoryItemId,
    uint256 quantity
  );

  function evefrontier__ephemeralToInventoryTransfer(
    uint256 smartObjectId,
    address ephInvOwner,
    TransferItem[] memory items
  ) external;

  function evefrontier__inventoryToEphemeralTransfer(
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) external;
}
