// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LocationData } from "../index.sol";

/**
 * @title ILocationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILocationSystem {
  function eveworld__saveLocation(uint256 smartObjectId, LocationData memory locationData) external;

  function eveworld__setSolarSystemId(uint256 smartObjectId, uint256 solarSystemId) external;

  function eveworld__setX(uint256 smartObjectId, uint256 x) external;

  function eveworld__setY(uint256 smartObjectId, uint256 y) external;

  function eveworld__setZ(uint256 smartObjectId, uint256 z) external;
}
