// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRiftSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRiftSystem {
  error RiftAlreadyExists();
  error RiftAlreadyCollapsed();

  function evefrontier__createRift(uint256 riftId, uint256 crudeAmount) external;

  function evefrontier__destroyRift(uint256 riftId) external;

  function evefrontier__getRiftClassId() external pure returns (uint256);
}
