// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CreateAndAnchorParams } from "../../namespaces/evefrontier/systems/deployable/types.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { TargetPriority, Turret, SmartTurretTarget, AggressionParams } from "../../namespaces/evefrontier/systems/smart-turret/types.sol";

/**
 * @title ISmartTurretSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISmartTurretSystem {
  function evefrontier__createAndAnchorTurret(CreateAndAnchorParams memory params) external;

  function evefrontier__configureTurret(uint256 smartObjectId, ResourceId systemId) external;

  function evefrontier__inProximity(
    uint256 smartObjectId,
    TargetPriority[] memory priorityQueue,
    Turret memory turret,
    SmartTurretTarget memory turretTarget
  ) external returns (TargetPriority[] memory updatedPriorityQueue);

  function evefrontier__aggression(
    AggressionParams memory params
  ) external returns (TargetPriority[] memory updatedPriorityQueue);

  function evefrontier__getSmartTurretClassId() external view returns (uint256);
}
