// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IStaticDataSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStaticDataSystem {
  function eveworld__createStaticData(uint256 entityId, string memory cid) external;

  function eveworld__createStaticDataMetadata(bytes32 classId, string memory name, string memory baseURI) external;

  function eveworld__setCid(uint256 entityId, string memory cid) external;

  function eveworld__setName(bytes32 classId, string memory name) external;

  function eveworld__setBaseURI(bytes32 classId, string memory baseURI) external;
}
