// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEntityCore
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntityCore {
  function eveworld__registerEntityType(uint8 entityTypeId, bytes32 entityType) external;

  function eveworld__registerEntity(uint256 entityId, uint8 entityType) external;

  function eveworld__registerEntities(uint256[] memory entityId, uint8[] memory entityType) external;

  function eveworld__registerEntityTypeAssociation(uint8 entityType, uint8 tagEntityType) external;

  function eveworld__tagEntity(uint256 entityId, uint256 entityTagId) external;

  function eveworld__tagEntities(uint256 entityId, uint256[] memory entityTagIds) external;

  function eveworld__removeEntityTag(uint256 entityId, uint256 entityTagId) external;
}
