// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";
import { HookType } from "./../../types.sol";

/**
 * @title IHookCore
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IHookCore {
  function eveworld__registerHook(ResourceId systemId, bytes4 functionId) external;

  function eveworld__addHook(uint256 hookId, HookType hookType, ResourceId systemId, bytes4 functionSelector) external;

  function eveworld__removeHook(
    uint256 hookId,
    HookType hookType,
    ResourceId systemId,
    bytes4 functionSelector
  ) external;

  function eveworld__associateHook(uint256 entityId, uint256 hookId) external;

  function eveworld__associateHooks(uint256 entityId, uint256[] memory hookIds) external;

  function eveworld__removeEntityHookAssociation(uint256 entityId, uint256 hookId) external;
}
