// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAccessControlSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAccessControlSystem {
  function onlyAdminHook(uint256 entityId) external;

  function onlyOwnerHook(uint256 smartObjectId) external;

  function createRole(bytes32 role, address roleAddress) external;

  function getOwner(uint256 smartObjectId) external returns (address owner);
}
