// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";

/**
 * @title IDelegationControlSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDelegationControlSystem {
  function verify(address, ResourceId systemId, bytes memory) external view returns (bool);

  function initDelegation(ResourceId namespaceId, address trustedForwarder) external;
}
