// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEntityRecordSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntityRecordSystem {
  function eveworld__createEntityRecord(uint256 entityId, uint256 itemId, uint256 typeId, uint256 volume) external;

  function eveworld__createEntityRecordOffchain(
    uint256 entityId,
    string memory name,
    string memory dappURL,
    string memory description
  ) external;

  function eveworld__setEntityMetadata(
    uint256 entityId,
    string memory name,
    string memory dappURL,
    string memory description
  ) external;

  function eveworld__setName(uint256 entityId, string memory name) external;

  function eveworld__setDappURL(uint256 entityId, string memory dappURL) external;

  function eveworld__setDescription(uint256 entityId, string memory description) external;
}
