// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TransferItem } from "../../modules/inventory/types.sol";

/**
 * @title IInventoryInteractSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInventoryInteractSystem {
  function eveworld__ephemeralToInventoryTransfer(uint256 smartObjectId, TransferItem[] memory items) external;

  function eveworld__inventoryToEphemeralTransfer(
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) external;

  function eveworld__setApprovedAccessList(uint256 smartObjectId, address[] memory accessList) external;

  function eveworld__setAllInventoryTransferAccess(uint256 smartObjectId, bool isEnforced) external;

  function eveworld__setEphemeralToInventoryTransferAccess(uint256 smartObjectId, bool isEnforced) external;

  function eveworld__setInventoryToEphemeralTransferAccess(uint256 smartObjectId, bool isEnforced) external;
}
