// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityRecordTableData } from "./../tables/EntityRecordTable.sol";
import { EntityRecordOffchainTableData } from "./../tables/EntityRecordOffchainTable.sol";
import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";

/**
 * @title ISmartCharacter
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISmartCharacter {
  error SmartCharacterERC721AlreadyInitialized();
  error SmartCharacterTokenCidCannotBeEmpty(uint256 characterId, string tokenCid);

  function eveworld__registerERC721Token(address tokenAddress) external;

  function eveworld__createCharacter(
    uint256 characterId,
    address characterAddress,
    EntityRecordTableData memory entityRecord,
    EntityRecordOffchainTableData memory entityRecordOffchain,
    string memory tokenCid
  ) external;

  function eveworld__characterSystemId() external view returns (ResourceId);
}
