// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GlobalStaticData } from "./tables/GlobalStaticData.sol";
import { Role } from "./tables/Role.sol";
