// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { InventoryItem } from "./../../types.sol";

/**
 * @title IEphemeralInventorySystem
 * @dev This interface is to make interacting with the underlying system easier via worldCall.
 */
interface IEphemeralInventorySystem {
  function setEphemeralInventoryCapacity(
    uint256 smartObjectId,
    address owner,
    uint256 ephemeralStorageCapacity
  ) external;

  function depositToEphemeralInventory(uint256 smartObjectId, InventoryItem[] memory items) external;

  function withdrawFromEphemeralInventory(uint256 smartObjectId, InventoryItem[] memory items) external;
}
