// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { InventoryItem } from "../types.sol";

/**
 * @title IInventoryInteract
 * @dev This interface is to make interacting with the underlying system easier via worldCall.
 */
interface IInventoryInteract {
  function inventoryToEphemeralTransfer(
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    InventoryItem[] memory items
  ) external;

  function ephemeralToInventoryTransfer(
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    InventoryItem[] memory items
  ) external;

  function configureInteractionHandler(uint256 smartObjectId, bytes memory interactionParams) external;
}
