// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Initialize } from "./tables/Initialize.sol";
import { InventoryByItem } from "./tables/InventoryByItem.sol";
import { OwnershipByObject } from "./tables/OwnershipByObject.sol";
import { Tenant } from "./tables/Tenant.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { SmartAssembly } from "./tables/SmartAssembly.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharactersByAccount } from "./tables/CharactersByAccount.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployableState, GlobalDeployableStateData } from "./tables/GlobalDeployableState.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
import { InventoryItemTransfer, InventoryItemTransferData } from "./tables/InventoryItemTransfer.sol";
import { EphemeralInvCapacity } from "./tables/EphemeralInvCapacity.sol";
import { EphemeralInventory, EphemeralInventoryData } from "./tables/EphemeralInventory.sol";
import { EphemeralInvItem, EphemeralInvItemData } from "./tables/EphemeralInvItem.sol";
import { InventoryByEphemeral, InventoryByEphemeralData } from "./tables/InventoryByEphemeral.sol";
import { EphemeralItemTransfer, EphemeralItemTransferData } from "./tables/EphemeralItemTransfer.sol";
import { SmartTurretConfig } from "./tables/SmartTurretConfig.sol";
import { SmartGateConfig, SmartGateConfigData } from "./tables/SmartGateConfig.sol";
import { SmartGateLink, SmartGateLinkData } from "./tables/SmartGateLink.sol";
import { KillMail, KillMailData } from "./tables/KillMail.sol";
