// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { WorldOwnership } from "./tables/WorldOwnership.sol";
import { AccountOwnership } from "./tables/AccountOwnership.sol";
import { OwnershipByObject } from "./tables/OwnershipByObject.sol";
import { InventoryByItem } from "./tables/InventoryByItem.sol";
import { Tenant } from "./tables/Tenant.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { SmartAssembly, SmartAssemblyData } from "./tables/SmartAssembly.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharactersByAccount } from "./tables/CharactersByAccount.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployableState, GlobalDeployableStateData } from "./tables/GlobalDeployableState.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
import { ObjectItemTransfer, ObjectItemTransferData } from "./tables/ObjectItemTransfer.sol";
import { EphemeralInvCapacity } from "./tables/EphemeralInvCapacity.sol";
import { ObjectByEphemeral } from "./tables/ObjectByEphemeral.sol";
import { ItemTransfer, ItemTransferData } from "./tables/ItemTransfer.sol";
import { SmartTurretConfig } from "./tables/SmartTurretConfig.sol";
import { SmartGateConfig, SmartGateConfigData } from "./tables/SmartGateConfig.sol";
import { SmartGateLink, SmartGateLinkData } from "./tables/SmartGateLink.sol";
