// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SmartAssembly, SmartAssemblyData } from "./tables/SmartAssembly.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharactersByAddress } from "./tables/CharactersByAddress.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployableState, GlobalDeployableStateData } from "./tables/GlobalDeployableState.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
import { EphemeralInvCapacity } from "./tables/EphemeralInvCapacity.sol";
import { EphemeralInv, EphemeralInvData } from "./tables/EphemeralInv.sol";
import { EphemeralInvItem, EphemeralInvItemData } from "./tables/EphemeralInvItem.sol";
import { ItemTransferOffchain, ItemTransferOffchainData } from "./tables/ItemTransferOffchain.sol";
import { SmartTurretConfig } from "./tables/SmartTurretConfig.sol";
import { SmartGateConfig, SmartGateConfigData } from "./tables/SmartGateConfig.sol";
import { SmartGateLink, SmartGateLinkData } from "./tables/SmartGateLink.sol";
