// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct HookTargetBeforeData {
  bool hasHook;
  ResourceId systemSelector;
  bytes4 functionSelector;
}

library HookTargetBefore {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "eveworld", name: "HookTargetBefore", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462657665776f726c64000000000000486f6f6b5461726765744265666f7265);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0025030001200400000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256, uint256)
  Schema constant _keySchema = Schema.wrap(0x004002001f1f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bool, bytes32, bytes4)
  Schema constant _valueSchema = Schema.wrap(0x00250300605f4300000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "hookId";
    keyNames[1] = "targetId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "hasHook";
    fieldNames[1] = "systemSelector";
    fieldNames[2] = "functionSelector";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get hasHook.
   */
  function getHasHook(uint256 hookId, uint256 targetId) internal view returns (bool hasHook) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get hasHook.
   */
  function _getHasHook(uint256 hookId, uint256 targetId) internal view returns (bool hasHook) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set hasHook.
   */
  function setHasHook(uint256 hookId, uint256 targetId, bool hasHook) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hasHook)), _fieldLayout);
  }

  /**
   * @notice Set hasHook.
   */
  function _setHasHook(uint256 hookId, uint256 targetId, bool hasHook) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hasHook)), _fieldLayout);
  }

  /**
   * @notice Get systemSelector.
   */
  function getSystemSelector(uint256 hookId, uint256 targetId) internal view returns (ResourceId systemSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return ResourceId.wrap(bytes32(_blob));
  }

  /**
   * @notice Get systemSelector.
   */
  function _getSystemSelector(uint256 hookId, uint256 targetId) internal view returns (ResourceId systemSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return ResourceId.wrap(bytes32(_blob));
  }

  /**
   * @notice Set systemSelector.
   */
  function setSystemSelector(uint256 hookId, uint256 targetId, ResourceId systemSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.setStaticField(
      _tableId,
      _keyTuple,
      1,
      abi.encodePacked(ResourceId.unwrap(systemSelector)),
      _fieldLayout
    );
  }

  /**
   * @notice Set systemSelector.
   */
  function _setSystemSelector(uint256 hookId, uint256 targetId, ResourceId systemSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(ResourceId.unwrap(systemSelector)), _fieldLayout);
  }

  /**
   * @notice Get functionSelector.
   */
  function getFunctionSelector(uint256 hookId, uint256 targetId) internal view returns (bytes4 functionSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (bytes4(_blob));
  }

  /**
   * @notice Get functionSelector.
   */
  function _getFunctionSelector(uint256 hookId, uint256 targetId) internal view returns (bytes4 functionSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (bytes4(_blob));
  }

  /**
   * @notice Set functionSelector.
   */
  function setFunctionSelector(uint256 hookId, uint256 targetId, bytes4 functionSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((functionSelector)), _fieldLayout);
  }

  /**
   * @notice Set functionSelector.
   */
  function _setFunctionSelector(uint256 hookId, uint256 targetId, bytes4 functionSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((functionSelector)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 hookId, uint256 targetId) internal view returns (HookTargetBeforeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 hookId, uint256 targetId) internal view returns (HookTargetBeforeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 hookId,
    uint256 targetId,
    bool hasHook,
    ResourceId systemSelector,
    bytes4 functionSelector
  ) internal {
    bytes memory _staticData = encodeStatic(hasHook, systemSelector, functionSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 hookId,
    uint256 targetId,
    bool hasHook,
    ResourceId systemSelector,
    bytes4 functionSelector
  ) internal {
    bytes memory _staticData = encodeStatic(hasHook, systemSelector, functionSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 hookId, uint256 targetId, HookTargetBeforeData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hasHook, _table.systemSelector, _table.functionSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 hookId, uint256 targetId, HookTargetBeforeData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hasHook, _table.systemSelector, _table.functionSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (bool hasHook, ResourceId systemSelector, bytes4 functionSelector) {
    hasHook = (_toBool(uint8(Bytes.getBytes1(_blob, 0))));

    systemSelector = ResourceId.wrap(Bytes.getBytes32(_blob, 1));

    functionSelector = (Bytes.getBytes4(_blob, 33));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (HookTargetBeforeData memory _table) {
    (_table.hasHook, _table.systemSelector, _table.functionSelector) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 hookId, uint256 targetId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 hookId, uint256 targetId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bool hasHook,
    ResourceId systemSelector,
    bytes4 functionSelector
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(hasHook, systemSelector, functionSelector);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bool hasHook,
    ResourceId systemSelector,
    bytes4 functionSelector
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(hasHook, systemSelector, functionSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 hookId, uint256 targetId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(hookId));
    _keyTuple[1] = bytes32(uint256(targetId));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
