// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CallAccess } from "./tables/CallAccess.sol";
import { AccessConfig, AccessConfigData } from "./tables/AccessConfig.sol";
import { Role, RoleData } from "./tables/Role.sol";
import { HasRole, HasRoleData } from "./tables/HasRole.sol";
import { Entity, EntityData } from "./tables/Entity.sol";
import { EntityTagMap, EntityTagMapData } from "./tables/EntityTagMap.sol";
import { Initialized } from "./tables/Initialized.sol";
